CREATE TABLE `CAR_DETAILS` (
  `id` int NOT NULL AUTO_INCREMENT,
  `vin` varchar(32) NOT NULL,
  `make` varchar(32) NOT NULL,
  `model` varchar(32) NOT NULL,
  `trim` varchar(32) DEFAULT NULL,
  `year` int NOT NULL,
  `stock_id` varchar(32) NOT NULL,
  `kbb_price` int DEFAULT NULL,
  `echo_park_price` int NOT NULL,
  `location` varchar(128) DEFAULT NULL,
  `mileage` int NOT NULL,
  `fuel_economy` int NOT NULL,
  `exterior_color` varchar(32) DEFAULT NULL,
  `interior_color` varchar(32) DEFAULT NULL,
  `transmission` varchar(32) NOT NULL DEFAULT 'Automatic',
  `engine` varchar(32) DEFAULT NULL,
  `horse_power` int DEFAULT NULL,
  `torque` int DEFAULT NULL,
  `drivetrain` varchar(32) DEFAULT NULL,
  `body_type` varchar(32) NOT NULL,
  `seating` int DEFAULT NULL,
  `hp_rpm` int DEFAULT NULL,
  `torque_rpm` int DEFAULT NULL,
  `fuel_economy_city` int DEFAULT NULL,
  `fuel_economy_highway` int DEFAULT NULL,
  `engine_volume` float DEFAULT NULL,
  `length` int NOT NULL,
  `width` int NOT NULL,
  `height` int NOT NULL,
  `front_leg_room` int NOT NULL,
  `rear_leg_room` int NOT NULL,
  `cargo_room` int NOT NULL,
  `others` varchar(10000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

